### ISSUE TITLE
'module' object has no attribute 'DecimalValidator' When using DecimalField

### ISSUE THREAD

**Issue by mrgaolei** [tomchristie/django-rest-framework#3580]
version 3.2.x is OK,
When I upgrade to 3.3, is broke.

**Comment by xordoquy** [comment]
We need more context or better a failing test case to understand what's going on.

**Comment by xordoquy** [comment]
Duplicate of #3568
