### ISSUE TITLE
Custom Exception documentation bug 

### ISSUE THREAD

**Issue by kunalbhagawati** [tomchristie/django-rest-framework#2737]
This is what is given in the the example for custom exceptions (v3.0.2):

    from rest_framework.views import exception_handler

    def custom_exception_handler(exc, context):
        # Call REST framework's default exception handler first,
        # to get the standard error response.
        response = exception_handler(exc, context)

        # Now add the HTTP status code to the response.
        if response is not None:
            response.data['status_code'] = response.status_code

        return response

But on raising an exception from the view, this returns the error:  
`custom_exception_handler() missing 1 required positional argument: 'context'`

So if we set `context=None`, like so:
`def custom_exception_handler(exc, context=None):`

The server now raises an exception:
`exception_handler() takes 1 positional argument but 2 were given`

Looking at the function `rest_framework.views.exception_handler`:  

    def exception_handler(exc):
        """
        Returns the response that should be used for any given exception.

        By default we handle the REST framework `APIException`, and also
        Django's built-in `ValidationError`, `Http404` and `PermissionDenied`
        exceptions.

        Any unhandled exceptions may return `None`, which will cause a 500 error
        to be raised.
        """

So I guess this could be a bug, since the source just contains one argument, or am i missing something?

**Comment by jpadilla** [comment]
This was officially introduced in #2236

**Comment by kunalbhagawati** [comment]
Okay.. So as Tom mentioned there, it has been taken care of. This is now to be considered closed then.

**Comment by sivakumarb-nalashaa** [comment]
This is my custom exception, while returning this class its throwing two exceptions. how to fix this issue?


def custom_exception_handler(exc, request):
    """
    Custom django rest framework exception handler that includes 'status_code' field in the
    responses.
    """
    # Call REST framework's default exception handler first
    response = exception_handler(exc)
    # Catch unexpected exceptions
    if response is None:
        if isinstance(exc, Exception):
            data = {'detail': 'A server error occurred.'}
            set_rollback()
            response = Response(data, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    # Now add the HTTP status code to the response.
    if response is not None:
        response.data['status_code'] = response.status_code
    return response

**Comment by rpkilby** [comment]
The exception handler returns an HTTP response, not an exception. You should return this response object, not raise it.
