### ISSUE TITLE
Clearer error when passing an iterable to serializer without setting `many=True`.

### ISSUE THREAD

**Issue by webzone-vn** [tomchristie/django-rest-framework#1914]
My project working well with django rest-framework ver 2.3.13 but today i had updated to newer version and I got error when serializers

"QuerySet' object has no attribute 'id'

**Comment by tomchristie** [comment]
Dropping the milestone from these as we don't *strictly* need them for 3.0.3.

**Comment by tomchristie** [comment]
Dropping this and the similar #2368. Don't think we've found entirely graceful approaches to either, and they're incremental improvements rather than strictly necessary, so I'd like to see them drop off our radar for the moment.
