### ISSUE TITLE
AttributeError: 'RegexURLPattern' object has no attribute '_callback'

### ISSUE THREAD

**Issue by pembo13** [tomchristie/django-rest-framework#4944]
## Steps to reproduce

1. Install `Django==1.10.6`
1. Install `djangorestframework==3.3.3`
1. Create a function based view (FBV)
1. Decorate the FBV with @api_view
1. Create a DefaultRouter (`router = routers.DefaultRouter()`)
1. Add urls

## Expected behavior

Routes with suffixes created.

## Actual behavior

AttributeError: 'RegexURLPattern' object has no attribute '_callback'

This code worked with `Django==1.9.7` and `djangorestframework==3.4.0`

## Relevant Stack Trace

      File "/virt/app/lib/python2.7/site-packages/rest_framework/routers.py", line 79, in urls
        self._urls = self.get_urls()
      File "/virt/app/lib/python2.7/site-packages/rest_framework/routers.py", line 321, in get_urls
        urls = format_suffix_patterns(urls)
      File "/virt/app/lib/python2.7/site-packages/rest_framework/urlpatterns.py", line 64, in format_suffix_patterns
        return apply_suffix_patterns(urlpatterns, suffix_pattern, suffix_required)
      File "/virt/app/lib/python2.7/site-packages/rest_framework/urlpatterns.py", line 27, in apply_suffix_patterns
        view = urlpattern._callback or urlpattern._callback_str
    AttributeError: 'RegexURLPattern' object has no attribute '_callback'

## Other Information

This particular use was very simple, and I switched to `SimpleRouter` temporarily, but that costs me the format extensions.

**Comment by xordoquy** [comment]
Django REST framework 3.3.x doesn't support Django 1.10.

**Comment by pembo13** [comment]
Sorry about that, I should have verified that first.
