### ISSUE TITLE
'HyperlinkedModelSerializer' with custom nested 'view_name's does not work in combination with 'depth'

### ISSUE THREAD

**Issue by stephenfin** [tomchristie/django-rest-framework#4854]
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

I have a number of `HyperlinkedModelSerializer`s. As I'm using manual URL definition, rather than a [router](http://www.django-rest-framework.org/api-guide/routers/), I must manually specify the `view_name` for each nested resource as part of `extra_kwargs`.

```python
class BookSerializer(HyperlinkedModelSerializer):

    class Meta:
        model = Book
        fields = ('id', 'url', 'author')
        read_only_fields = fields
        extra_kwargs = {
            'url': {'view_name': 'api-book-detail'},
            'author': {'view_name': 'api-person-detail'},
        }
```

This will result in an output like so:

```json
{
    "id": 1,
    "url": "http://example.com/api/v1/books/1",
    "author": "http://example.com/api/v1/authors/1"
}
```

This took me a while to figure out but pretty much works as expected. However, I now wish to provide a little more detail in response by nesting real objects in the response. It would appear that the `depth` meta key is the correct way to do this, like so:

```python
class BookSerializer(HyperlinkedModelSerializer):

    class Meta:
        model = Book
        fields = ('id', 'url', 'author')
        read_only_fields = fields
        depth = 1
        extra_kwargs = {
            'url': {'view_name': 'api-book-detail'},
            'author': {'view_name': 'api-author-detail'},
        }
```

However, this fails.

## Expected behavior

I would expect to see a nested response like so:

```json
{
    "id": 1,
    "url": "http://example.com/api/v1/books/1",
    "author": {
        "id": 1,
        "url": "http://example.com/api/v1/authors/1",
        "name": "John Doe",
        "user": "http://example.com/api/v1/users/1"
     }
}
```

## Actual behavior

I get an exception like so:

```python
TypeError: __init__() got an unexpected keyword argument 'view_name'
```

If I remove the `author` field from `extra_kwargs`, this changes to:

```python
django.core.exceptions.ImproperlyConfigured: Could not resolve URL for hyperlinked relationship using view name "author-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.
```

Seeing as these two features work independently, I can't see why they wouldn't work together.

**Comment by tomchristie** [comment]
You'd need to set the `view_name` on a nested author serializer, for both the `url` and `user` fields.

**Comment by TZanke** [comment]
This is correct, but to declare `view_name` in a sub serializer i have to set the nested serializer explicitly in the first serializer. But this disables the depth logic to hyperlink *OR* nest a sub serializer depending on the depth attribute.

How to define the sub serializer class without setting the nested serializer explicitly? Is it possible with extra_kwargs?!
